export enum e_ident {
	MAG0 = 0x1,
	MAG1 = 0x2,
	MAG2 = 0x3,
	MAG3 = 0x4,
	CLASS = 0x5,
	DATA = 0x6,
	VERSION = 0x7,
	OSABI = 0x8,
	ABIVERSION = 0x9,
}

export enum EI_OSABI {
	NONE = 0 /* UNIX System V ABI */,
	HPUX = 1 /* HP-UX operating system */,
	NETBSD = 2 /* NetBSD */,
	GNU = 3 /* GNU */,
	LINUX = 3 /* Alias for ELFOSABI_GNU */,
	SOLARIS = 6 /* Solaris */,
	AIX = 7 /* AIX */,
	IRIX = 8 /* IRIX */,
	FREEBSD = 9 /* FreeBSD */,
	TRU64 = 10 /* TRU64 UNIX */,
	MODESTO = 11 /* Novell Modesto */,
	OPENBSD = 12 /* OpenBSD */,
	OPENVMS = 13 /* OpenVMS */,
	NSK = 14 /* Hewlett-Packard Non-Stop Kernel */,
	AROS = 15 /* AROS */,
	FENIXOS = 16 /* FenixOS */,
	CLOUDABI = 17 /* Nuxi CloudABI */,
	OPENVOS = 18 /* Stratus Technologies OpenVOS */,
	C6000_ELFABI = 64 /* Bare-metal TMS320C6000 */,
	AMDGPU_HSA = 64 /* AMD HSA Runtime */,
	C6000_LINUX = 65 /* Linux TMS320C6000 */,
	AMDGPU_PAL = 65 /* AMD PAL Runtime */,
	ARM_FDPIC = 65 /* ARM FDPIC */,
	AMDGPU_MESA3D = 66 /* AMD Mesa3D Runtime */,
	ARM = 97 /* ARM */,
	STANDALONE = 255 /* Standalone (embedded) application */,
}

export const EI_OSABI_STRINGS: string[] = [];
EI_OSABI_STRINGS[EI_OSABI.NONE] = 'System V ABI';
EI_OSABI_STRINGS[EI_OSABI.HPUX] = 'HP-UX operating system';
EI_OSABI_STRINGS[EI_OSABI.NETBSD] = 'NetBSD';
EI_OSABI_STRINGS[EI_OSABI.GNU] = 'Linux/Gnu';
EI_OSABI_STRINGS[EI_OSABI.LINUX] = 'Alias for ELFOSABI_GNU';
EI_OSABI_STRINGS[EI_OSABI.SOLARIS] = 'Solaris';
EI_OSABI_STRINGS[EI_OSABI.AIX] = 'AIX';
EI_OSABI_STRINGS[EI_OSABI.IRIX] = 'IRIX';
EI_OSABI_STRINGS[EI_OSABI.FREEBSD] = 'FreeBSD';
EI_OSABI_STRINGS[EI_OSABI.TRU64] = ' TRU64 UNIX';
EI_OSABI_STRINGS[EI_OSABI.MODESTO] = 'Novell Modesto';
EI_OSABI_STRINGS[EI_OSABI.OPENBSD] = 'OpenBSD';
EI_OSABI_STRINGS[EI_OSABI.OPENVMS] = 'OpenVMS';
EI_OSABI_STRINGS[EI_OSABI.NSK] = 'Hewlett-Packard Non-Stop Kernel';
EI_OSABI_STRINGS[EI_OSABI.AROS] = 'AROS';
EI_OSABI_STRINGS[EI_OSABI.FENIXOS] = 'FenixOS';
EI_OSABI_STRINGS[EI_OSABI.CLOUDABI] = 'Nuxi CloudABI';
EI_OSABI_STRINGS[EI_OSABI.OPENVOS] = 'Stratus Technologies OpenVOS';
EI_OSABI_STRINGS[EI_OSABI.C6000_ELFABI] = 'Bare-metal TMS320C6000';
EI_OSABI_STRINGS[EI_OSABI.AMDGPU_HSA] = 'AMD HSA Runtime';
EI_OSABI_STRINGS[EI_OSABI.C6000_LINUX] = 'Linux TMS320C6000';
EI_OSABI_STRINGS[EI_OSABI.AMDGPU_PAL] = 'AMD PAL Runtime';
EI_OSABI_STRINGS[EI_OSABI.ARM_FDPIC] = 'ARM FDPIC';
EI_OSABI_STRINGS[EI_OSABI.AMDGPU_MESA3D] = 'AMD Mesa3D Runtime';
EI_OSABI_STRINGS[EI_OSABI.ARM] = 'ARM';
EI_OSABI_STRINGS[EI_OSABI.STANDALONE] = 'Standalone (embedded) application';

//Note in C these are prefixed with ET_
export enum e_type {
	NONE = 0x00, //Unknown.
	REL = 0x01, //Relocatable file.
	EXEC = 0x02, //Executable file.
	DYN = 0x03, //Shared object.
	CORE = 0x04, //Core file.
	//[LOOS - ISOS] Reserved inclusive range. Operating system specific.
	LOOS = 0xfe00,
	HIOS = 0xfeff,
	//[LOPROC - HIPROC] Reserved inclusive range. Processor specific.
	LOPROC = 0xff00,
	HIPROC = 0xffff,
}

export enum e_machine {
	NONE = 0 /* No machine */,
	M32 = 1 /* AT&T WE 32100 */,
	SPARC = 2 /* SUN SPARC */,
	_386 = 3 /* Intel 80386 */,
	_68K = 4 /* Motorola m68k family */,
	_88K = 5 /* Motorola m88k family */,
	IAMCU = 6 /* Intel MCU */,
	_860 = 7 /* Intel 80860 */,
	MIPS = 8 /* MIPS R3000 (officially, big-endian only) */,
	S370 = 9 /* IBM System/370 */,
	MIPS_RS3_LE = 10 /* MIPS R3000 little-endian (Oct 4 1999 Draft).  Deprecated.  */,
	OLD_SPARCV9 = 11 /* Old version of Sparc v9, from before the ABI.  Deprecated.  */,
	res011 = 11 /* Reserved */,
	res012 = 12 /* Reserved */,
	res013 = 13 /* Reserved */,
	res014 = 14 /* Reserved */,
	PARISC = 15 /* HPPA */,
	res016 = 16 /* Reserved */,
	PPC_OLD = 17 /* Old version of PowerPC.  Deprecated.  */,
	VPP550 = 17 /* Fujitsu VPP500 */,
	SPARC32PLUS = 18 /* Sun's "v8plus" */,
	_960 = 19 /* Intel 80960 */,
	PPC = 20 /* PowerPC */,
	PPC64 = 21 /* 64-bit PowerPC */,
	S390 = 22 /* IBM S/390 */,
	SPU = 23 /* Sony/Toshiba/IBM SPU */,
	res024 = 24 /* Reserved */,
	res025 = 25 /* Reserved */,
	res026 = 26 /* Reserved */,
	res027 = 27 /* Reserved */,
	res028 = 28 /* Reserved */,
	res029 = 29 /* Reserved */,
	res030 = 30 /* Reserved */,
	res031 = 31 /* Reserved */,
	res032 = 32 /* Reserved */,
	res033 = 33 /* Reserved */,
	res034 = 34 /* Reserved */,
	res035 = 35 /* Reserved */,
	V800 = 36 /* NEC V800 series */,
	FR20 = 37 /* Fujitsu FR20 */,
	RH32 = 38 /* TRW RH32 */,
	MCORE = 39 /* Motorola M*Core */ /* May also be taken by Fujitsu MMA */,
	RCE = 39 /* Old name for MCore */,
	ARM = 40 /* ARM */,
	OLD_ALPHA = 41 /* Digital Alpha */,
	SH = 42 /* Renesas (formerly Hitachi) / SuperH SH */,
	SPARCV9 = 43 /* SPARC v9 64-bit */,
	TRICORE = 44 /* Siemens Tricore embedded processor */,
	ARC = 45 /* ARC Cores */,
	H8_300 = 46 /* Renesas (formerly Hitachi) H8/300 */,
	H8_300H = 47 /* Renesas (formerly Hitachi) H8/300H */,
	H8S = 48 /* Renesas (formerly Hitachi) H8S */,
	H8_500 = 49 /* Renesas (formerly Hitachi) H8/500 */,
	IA_64 = 50 /* Intel IA-64 Processor */,
	MIPS_X = 51 /* Stanford MIPS-X */,
	COLDFIRE = 52 /* Motorola Coldfire */,
	_68HC12 = 53 /* Motorola M68HC12 */,
	MMA = 54 /* Fujitsu Multimedia Accelerator */,
	PCP = 55 /* Siemens PCP */,
	NCPU = 56 /* Sony nCPU embedded RISC processor */,
	NDR1 = 57 /* Denso NDR1 microprocessor */,
	STARCORE = 58 /* Motorola Star*Core processor */,
	ME16 = 59 /* Toyota ME16 processor */,
	ST100 = 60 /* STMicroelectronics ST100 processor */,
	TINYJ = 61 /* Advanced Logic Corp. TinyJ embedded processor */,
	X86_64 = 62 /* Advanced Micro Devices X86-64 processor */,
	PDSP = 63 /* Sony DSP Processor */,
	PDP10 = 64 /* Digital Equipment Corp. PDP-10 */,
	PDP11 = 65 /* Digital Equipment Corp. PDP-11 */,
	FX66 = 66 /* Siemens FX66 microcontroller */,
	ST9PLUS = 67 /* STMicroelectronics ST9+ 8/16 bit microcontroller */,
	ST7 = 68 /* STMicroelectronics ST7 8-bit microcontroller */,
	_68HC16 = 69 /* Motorola MC68HC16 Microcontroller */,
	_68HC11 = 70 /* Motorola MC68HC11 Microcontroller */,
	_68HC08 = 71 /* Motorola MC68HC08 Microcontroller */,
	_68HC05 = 72 /* Motorola MC68HC05 Microcontroller */,
	SVX = 73 /* Silicon Graphics SVx */,
	ST19 = 74 /* STMicroelectronics ST19 8-bit cpu */,
	VAX = 75 /* Digital VAX */,
	CRIS = 76 /* Axis Communications 32-bit embedded processor */,
	JAVELIN = 77 /* Infineon Technologies 32-bit embedded cpu */,
	FIREPATH = 78 /* Element 14 64-bit DSP processor */,
	ZSP = 79 /* LSI Logic's 16-bit DSP processor */,
	MMIX = 80 /* Donald Knuth's educational 64-bit processor */,
	HUANY = 81 /* Harvard's machine-independent format */,
	PRISM = 82 /* SiTera Prism */,
	AVR = 83 /* Atmel AVR 8-bit microcontroller */,
	FR30 = 84 /* Fujitsu FR30 */,
	D10V = 85 /* Mitsubishi D10V */,
	D30V = 86 /* Mitsubishi D30V */,
	V850 = 87 /* Renesas V850 (formerly NEC V850) */,
	M32R = 88 /* Renesas M32R (formerly Mitsubishi M32R) */,
	MN10300 = 89 /* Matsushita MN10300 */,
	MN10200 = 90 /* Matsushita MN10200 */,
	PJ = 91 /* picoJava */,
	OR1K = 92 /* OpenRISC 1000 32-bit embedded processor */,
	ARC_COMPACT = 93 /* ARC International ARCompact processor */,
	XTENSA = 94 /* Tensilica Xtensa Architecture */,
	SCORE_OLD = 95 /* Old Sunplus S+core7 backend magic number. Written in the absence of an ABI.  */,
	VIDEOCORE = 95 /* Alphamosaic VideoCore processor */,
	TMM_GPP = 96 /* Thompson Multimedia General Purpose Processor */,
	NS32K = 97 /* National Semiconductor 32000 series */,
	TPC = 98 /* Tenor Network TPC processor */,
	PJ_OLD = 99 /* Old value for picoJava.  Deprecated.  */,
	SNP1K = 99 /* Trebia SNP 1000 processor */,
	ST200 = 100 /* STMicroelectronics ST200 microcontroller */,
	IP2K = 101 /* Ubicom IP2022 micro controller */,
	MAX = 102 /* MAX Processor */,
	CR = 103 /* National Semiconductor CompactRISC */,
	F2MC16 = 104 /* Fujitsu F2MC16 */,
	MSP430 = 105 /* TI msp430 micro controller */,
	BLACKFIN = 106 /* ADI Blackfin */,
	SE_C33 = 107 /* S1C33 Family of Seiko Epson processors */,
	SEP = 108 /* Sharp embedded microprocessor */,
	ARCA = 109 /* Arca RISC Microprocessor */,
	UNICORE = 110 /* Microprocessor series from PKU-Unity Ltd. and MPRC of Peking University */,
	EXCESS = 111 /* eXcess: 16/32/64-bit configurable embedded CPU */,
	DXP = 112 /* Icera Semiconductor Inc. Deep Execution Processor */,
	ALTERA_NIOS2 = 113 /* Altera Nios II soft-core processor */,
	CRX = 114 /* National Semiconductor CRX */,
	CR16_OLD = 115 /* Old, value for National Semiconductor CompactRISC.  Deprecated.  */,
	XGATE = 115 /* Motorola XGATE embedded processor */,
	C166 = 116 /* Infineon C16x/XC16x processor */,
	M16C = 117 /* Renesas M16C series microprocessors */,
	DSPIC30F = 118 /* Microchip Technology dsPIC30F Digital Signal Controller */,
	CE = 119 /* Freescale Communication Engine RISC core */,
	M32C = 120 /* Renesas M32C series microprocessors */,
	res121 = 121 /* Reserved */,
	res122 = 122 /* Reserved */,
	res123 = 123 /* Reserved */,
	res124 = 124 /* Reserved */,
	res125 = 125 /* Reserved */,
	res126 = 126 /* Reserved */,
	res127 = 127 /* Reserved */,
	res128 = 128 /* Reserved */,
	res129 = 129 /* Reserved */,
	res130 = 130 /* Reserved */,
	TSK3000 = 131 /* Altium TSK3000 core */,
	RS08 = 132 /* Freescale RS08 embedded processor */,
	res133 = 133 /* Reserved */,
	ECOG2 = 134 /* Cyan Technology eCOG2 microprocessor */,
	SCORE = 135 /* Sunplus Score */,
	SCORE7 = 135 /* Sunplus S+core7 RISC processor */,
	DSP24 = 136 /* New Japan Radio (NJR) 24-bit DSP Processor */,
	VIDEOCORE3 = 137 /* Broadcom VideoCore III processor */,
	LATTICEMICO32 = 138 /* RISC processor for Lattice FPGA architecture */,
	SE_C17 = 139 /* Seiko Epson C17 family */,
	TI_C6000 = 140 /* Texas Instruments TMS320C6000 DSP family */,
	TI_C2000 = 141 /* Texas Instruments TMS320C2000 DSP family */,
	TI_C5500 = 142 /* Texas Instruments TMS320C55x DSP family */,
	res143 = 143 /* Reserved */,
	TI_PRU = 144 /* Texas Instruments Programmable Realtime Unit */,
	res145 = 145 /* Reserved */,
	res146 = 146 /* Reserved */,
	res147 = 147 /* Reserved */,
	res148 = 148 /* Reserved */,
	res149 = 149 /* Reserved */,
	res150 = 150 /* Reserved */,
	res151 = 151 /* Reserved */,
	res152 = 152 /* Reserved */,
	res153 = 153 /* Reserved */,
	res154 = 154 /* Reserved */,
	res155 = 155 /* Reserved */,
	res156 = 156 /* Reserved */,
	res157 = 157 /* Reserved */,
	res158 = 158 /* Reserved */,
	res159 = 159 /* Reserved */,
	MMDSP_PLUS = 160 /* STMicroelectronics 64bit VLIW Data Signal Processor */,
	CYPRESS_M8C = 161 /* Cypress M8C microprocessor */,
	R32C = 162 /* Renesas R32C series microprocessors */,
	TRIMEDIA = 163 /* NXP Semiconductors TriMedia architecture family */,
	QDSP6 = 164 /* QUALCOMM DSP6 Processor */,
	_8051 = 165 /* Intel 8051 and variants */,
	STXP7X = 166 /* STMicroelectronics STxP7x family */,
	NDS32 = 167 /* Andes Technology compact code size embedded RISC processor family */,
	ECOG1 = 168 /* Cyan Technology eCOG1X family */,
	ECOG1X = 168 /* Cyan Technology eCOG1X family */,
	MAXQ30 = 169 /* Dallas Semiconductor MAXQ30 Core Micro-controllers */,
	XIMO16 = 170 /* New Japan Radio (NJR) 16-bit DSP Processor */,
	MANIK = 171 /* M2000 Reconfigurable RISC Microprocessor */,
	CRAYNV2 = 172 /* Cray Inc. NV2 vector architecture */,
	RX = 173 /* Renesas RX family */,
	METAG = 174 /* Imagination Technologies Meta processor architecture */,
	MCST_ELBRUS = 175 /* MCST Elbrus general purpose hardware architecture */,
	ECOG16 = 176 /* Cyan Technology eCOG16 family */,
	CR16 = 177 /* National Semiconductor CompactRISC 16-bit processor */,
	ETPU = 178 /* Freescale Extended Time Processing Unit */,
	SLE9X = 179 /* Infineon Technologies SLE9X core */,
	L1OM = 180 /* Intel L1OM */,
	K1OM = 181 /* Intel K1OM */,
	INTEL182 = 182 /* Reserved by Intel */,
	AARCH64 = 183 /* ARM 64-bit architecture */,
	ARM184 = 184 /* Reserved by ARM */,
	AVR32 = 185 /* Atmel Corporation 32-bit microprocessor family */,
	STM8 = 186 /* STMicroeletronics STM8 8-bit microcontroller */,
	TILE64 = 187 /* Tilera TILE64 multicore architecture family */,
	TILEPRO = 188 /* Tilera TILEPro multicore architecture family */,
	MICROBLAZE = 189 /* Xilinx MicroBlaze 32-bit RISC soft processor core */,
	CUDA = 190 /* NVIDIA CUDA architecture */,
	TILEGX = 191 /* Tilera TILE-Gx multicore architecture family */,
	CLOUDSHIELD = 192 /* CloudShield architecture family */,
	COREA_1ST = 193 /* KIPO-KAIST Core-A 1st generation processor family */,
	COREA_2ND = 194 /* KIPO-KAIST Core-A 2nd generation processor family */,
	ARC_COMPACT2 = 195 /* Synopsys ARCompact V2 */,
	OPEN8 = 196 /* Open8 8-bit RISC soft processor core */,
	RL78 = 197 /* Renesas RL78 family.  */,
	VIDEOCORE5 = 198 /* Broadcom VideoCore V processor */,
	_78K0R = 199 /* Renesas 78K0R.  */,
	_56800EX = 200 /* Freescale 56800EX Digital Signal Controller (DSC) */,
	BA1 = 201 /* Beyond BA1 CPU architecture */,
	BA2 = 202 /* Beyond BA2 CPU architecture */,
	XCORE = 203 /* XMOS xCORE processor family */,
	MCHP_PIC = 204 /* Microchip 8-bit PIC(r) family */,
	INTELGT = 205 /* Intel Graphics Technology */,
	INTEL206 = 206 /* Reserved by Intel */,
	INTEL207 = 207 /* Reserved by Intel */,
	INTEL208 = 208 /* Reserved by Intel */,
	INTEL209 = 209 /* Reserved by Intel */,
	KM32 = 210 /* KM211 KM32 32-bit processor */,
	KMX32 = 211 /* KM211 KMX32 32-bit processor */,
	KMX16 = 212 /* KM211 KMX16 16-bit processor */,
	KMX8 = 213 /* KM211 KMX8 8-bit processor */,
	KVARC = 214 /* KM211 KVARC processor */,
	CDP = 215 /* Paneve CDP architecture family */,
	COGE = 216 /* Cognitive Smart Memory Processor */,
	COOL = 217 /* Bluechip Systems CoolEngine */,
	NORC = 218 /* Nanoradio Optimized RISC */,
	CSR_KALIMBA = 219 /* CSR Kalimba architecture family */,
	Z80 = 220 /* Zilog Z80 */,
	VISIUM = 221 /* Controls and Data Services VISIUMcore processor */,
	FT32 = 222 /* FTDI Chip FT32 high performance 32-bit RISC architecture */,
	MOXIE = 223 /* Moxie processor family */,
	AMDGPU = 224 /* AMD GPU architecture */,
	RISCV = 243 /* RISC-V */,
	LANAI = 244 /* Lanai 32-bit processor.  */,
	CEVA = 245 /* CEVA Processor Architecture Family */,
	CEVA_X2 = 246 /* CEVA X2 Processor Family */,
	BPF = 247 /* Linux BPF – in-kernel virtual machine.  */,
	GRAPHCORE_IPU = 248 /* Graphcore Intelligent Processing Unit */,
	IMG1 = 249 /* Imagination Technologies */,
	NFP = 250 /* Netronome Flow Processor.  */,
	VE = 251 /* NEC Vector Engine */,
	CSKY = 252 /* C-SKY processor family.  */,
	ARC_COMPACT3_64 = 253 /* Synopsys ARCv2.3 64-bit */,
	MCS6502 = 254 /* MOS Technology MCS 6502 processor */,
	ARC_COMPACT3 = 255 /* Synopsys ARCv2.3 32-bit */,
	KVX = 256 /* Kalray VLIW core of the MPPA processor family */,
	_65816 = 257 /* WDC 65816/65C816 */,
	LOONGARCH = 258 /* LoongArch */,
	KF32 = 259 /* ChipON KungFu32 */,
	U16_U8CORE = 260 /* LAPIS nX-U16/U8 */,
	TACHYUM = 261 /* Tachyum */,
	_56800EF = 262 /* NXP 56800EF Digital Signal Controller (DSC) */,
}

export const e_machine_strings: string[] = [];
e_machine_strings[e_machine.NONE] = 'No machine';
e_machine_strings[e_machine.M32] = 'AT&T WE 32100';
e_machine_strings[e_machine.SPARC] = 'SUN SPARC';
e_machine_strings[e_machine._386] = 'Intel 80386';
e_machine_strings[e_machine._68K] = 'Motorola m68k family';
e_machine_strings[e_machine._88K] = 'Motorola m88k family';
e_machine_strings[e_machine.IAMCU] = 'Intel MCU';
e_machine_strings[e_machine._860] = 'Intel 80860';
e_machine_strings[e_machine.MIPS] = 'MIPS R3000 (officially, big-endian only)';
e_machine_strings[e_machine.S370] = 'IBM System/370';
e_machine_strings[e_machine.MIPS_RS3_LE] = 'MIPS R3000 little-endian (Oct 4 1999 Draft).  Deprecated. ';
e_machine_strings[e_machine.OLD_SPARCV9] = 'Old version of Sparc v9, from before the ABI.  Deprecated. ';
e_machine_strings[e_machine.res011] = 'Reserved';
e_machine_strings[e_machine.res012] = 'Reserved';
e_machine_strings[e_machine.res013] = 'Reserved';
e_machine_strings[e_machine.res014] = 'Reserved';
e_machine_strings[e_machine.PARISC] = 'HPPA';
e_machine_strings[e_machine.res016] = 'Reserved';
e_machine_strings[e_machine.PPC_OLD] = 'Old version of PowerPC.  Deprecated. ';
e_machine_strings[e_machine.VPP550] = 'Fujitsu VPP500';
e_machine_strings[e_machine.SPARC32PLUS] = 'Sun\'s "v8plus"';
e_machine_strings[e_machine._960] = 'Intel 80960';
e_machine_strings[e_machine.PPC] = 'PowerPC';
e_machine_strings[e_machine.PPC64] = '64-bit PowerPC';
e_machine_strings[e_machine.S390] = 'IBM S/390';
e_machine_strings[e_machine.SPU] = 'Sony/Toshiba/IBM SPU';
e_machine_strings[e_machine.res024] = 'Reserved';
e_machine_strings[e_machine.res025] = 'Reserved';
e_machine_strings[e_machine.res026] = 'Reserved';
e_machine_strings[e_machine.res027] = 'Reserved';
e_machine_strings[e_machine.res028] = 'Reserved';
e_machine_strings[e_machine.res029] = 'Reserved';
e_machine_strings[e_machine.res030] = 'Reserved';
e_machine_strings[e_machine.res031] = 'Reserved';
e_machine_strings[e_machine.res032] = 'Reserved';
e_machine_strings[e_machine.res033] = 'Reserved';
e_machine_strings[e_machine.res034] = 'Reserved';
e_machine_strings[e_machine.res035] = 'Reserved';
e_machine_strings[e_machine.V800] = 'NEC V800 series';
e_machine_strings[e_machine.FR20] = 'Fujitsu FR20';
e_machine_strings[e_machine.RH32] = 'TRW RH32';
e_machine_strings[e_machine.MCORE] = 'Motorola M*Core */ /* May also be taken by Fujitsu MMA';
e_machine_strings[e_machine.RCE] = 'Old name for MCore';
e_machine_strings[e_machine.ARM] = 'ARM';
e_machine_strings[e_machine.OLD_ALPHA] = 'Digital Alpha';
e_machine_strings[e_machine.SH] = 'Renesas (formerly Hitachi) / SuperH SH';
e_machine_strings[e_machine.SPARCV9] = 'SPARC v9 64-bit';
e_machine_strings[e_machine.TRICORE] = 'Siemens Tricore embedded processor';
e_machine_strings[e_machine.ARC] = 'ARC Cores';
e_machine_strings[e_machine.H8_300] = 'Renesas (formerly Hitachi) H8/300';
e_machine_strings[e_machine.H8_300H] = 'Renesas (formerly Hitachi) H8/300H';
e_machine_strings[e_machine.H8S] = 'Renesas (formerly Hitachi) H8S';
e_machine_strings[e_machine.H8_500] = 'Renesas (formerly Hitachi) H8/500';
e_machine_strings[e_machine.IA_64] = 'Intel IA-64 Processor';
e_machine_strings[e_machine.MIPS_X] = 'Stanford MIPS-X';
e_machine_strings[e_machine.COLDFIRE] = 'Motorola Coldfire';
e_machine_strings[e_machine._68HC12] = 'Motorola M68HC12';
e_machine_strings[e_machine.MMA] = 'Fujitsu Multimedia Accelerator';
e_machine_strings[e_machine.PCP] = 'Siemens PCP';
e_machine_strings[e_machine.NCPU] = 'Sony nCPU embedded RISC processor';
e_machine_strings[e_machine.NDR1] = 'Denso NDR1 microprocessor';
e_machine_strings[e_machine.STARCORE] = 'Motorola Star*Core processor';
e_machine_strings[e_machine.ME16] = 'Toyota ME16 processor';
e_machine_strings[e_machine.ST100] = 'STMicroelectronics ST100 processor';
e_machine_strings[e_machine.TINYJ] = 'Advanced Logic Corp. TinyJ embedded processor';
e_machine_strings[e_machine.X86_64] = 'Advanced Micro Devices X86-64 processor';
e_machine_strings[e_machine.PDSP] = 'Sony DSP Processor';
e_machine_strings[e_machine.PDP10] = 'Digital Equipment Corp. PDP-10';
e_machine_strings[e_machine.PDP11] = 'Digital Equipment Corp. PDP-11';
e_machine_strings[e_machine.FX66] = 'Siemens FX66 microcontroller';
e_machine_strings[e_machine.ST9PLUS] = 'STMicroelectronics ST9+ 8/16 bit microcontroller';
e_machine_strings[e_machine.ST7] = 'STMicroelectronics ST7 8-bit microcontroller';
e_machine_strings[e_machine._68HC16] = 'Motorola MC68HC16 Microcontroller';
e_machine_strings[e_machine._68HC11] = 'Motorola MC68HC11 Microcontroller';
e_machine_strings[e_machine._68HC08] = 'Motorola MC68HC08 Microcontroller';
e_machine_strings[e_machine._68HC05] = 'Motorola MC68HC05 Microcontroller';
e_machine_strings[e_machine.SVX] = 'Silicon Graphics SVx';
e_machine_strings[e_machine.ST19] = 'STMicroelectronics ST19 8-bit cpu';
e_machine_strings[e_machine.VAX] = 'Digital VAX';
e_machine_strings[e_machine.CRIS] = 'Axis Communications 32-bit embedded processor';
e_machine_strings[e_machine.JAVELIN] = 'Infineon Technologies 32-bit embedded cpu';
e_machine_strings[e_machine.FIREPATH] = 'Element 14 64-bit DSP processor';
e_machine_strings[e_machine.ZSP] = "LSI Logic's 16-bit DSP processor";
e_machine_strings[e_machine.MMIX] = "Donald Knuth's educational 64-bit processor";
e_machine_strings[e_machine.HUANY] = "Harvard's machine-independent format";
e_machine_strings[e_machine.PRISM] = 'SiTera Prism';
e_machine_strings[e_machine.AVR] = 'Atmel AVR 8-bit microcontroller';
e_machine_strings[e_machine.FR30] = 'Fujitsu FR30';
e_machine_strings[e_machine.D10V] = 'Mitsubishi D10V';
e_machine_strings[e_machine.D30V] = 'Mitsubishi D30V';
e_machine_strings[e_machine.V850] = 'Renesas V850 (formerly NEC V850)';
e_machine_strings[e_machine.M32R] = 'Renesas M32R (formerly Mitsubishi M32R)';
e_machine_strings[e_machine.MN10300] = 'Matsushita MN10300';
e_machine_strings[e_machine.MN10200] = 'Matsushita MN10200';
e_machine_strings[e_machine.PJ] = 'picoJava';
e_machine_strings[e_machine.OR1K] = 'OpenRISC 1000 32-bit embedded processor';
e_machine_strings[e_machine.ARC_COMPACT] = 'ARC International ARCompact processor';
e_machine_strings[e_machine.XTENSA] = 'Tensilica Xtensa Architecture';
e_machine_strings[e_machine.SCORE_OLD] = 'Old Sunplus S+core7 backend magic number. Written in the absence of an ABI. ';
e_machine_strings[e_machine.VIDEOCORE] = 'Alphamosaic VideoCore processor';
e_machine_strings[e_machine.TMM_GPP] = 'Thompson Multimedia General Purpose Processor';
e_machine_strings[e_machine.NS32K] = 'National Semiconductor 32000 series';
e_machine_strings[e_machine.TPC] = 'Tenor Network TPC processor';
e_machine_strings[e_machine.PJ_OLD] = 'Old value for picoJava.  Deprecated. ';
e_machine_strings[e_machine.SNP1K] = 'Trebia SNP 1000 processor';
e_machine_strings[e_machine.ST200] = 'STMicroelectronics ST200 microcontroller';
e_machine_strings[e_machine.IP2K] = 'Ubicom IP2022 micro controller';
e_machine_strings[e_machine.MAX] = 'MAX Processor';
e_machine_strings[e_machine.CR] = 'National Semiconductor CompactRISC';
e_machine_strings[e_machine.F2MC16] = 'Fujitsu F2MC16';
e_machine_strings[e_machine.MSP430] = 'TI msp430 micro controller';
e_machine_strings[e_machine.BLACKFIN] = 'ADI Blackfin';
e_machine_strings[e_machine.SE_C33] = 'S1C33 Family of Seiko Epson processors';
e_machine_strings[e_machine.SEP] = 'Sharp embedded microprocessor';
e_machine_strings[e_machine.ARCA] = 'Arca RISC Microprocessor';
e_machine_strings[e_machine.UNICORE] = 'Microprocessor series from PKU-Unity Ltd. and MPRC of Peking University';
e_machine_strings[e_machine.EXCESS] = 'eXcess: 16/32/64-bit configurable embedded CPU';
e_machine_strings[e_machine.DXP] = 'Icera Semiconductor Inc. Deep Execution Processor';
e_machine_strings[e_machine.ALTERA_NIOS2] = 'Altera Nios II soft-core processor';
e_machine_strings[e_machine.CRX] = 'National Semiconductor CRX';
e_machine_strings[e_machine.CR16_OLD] = 'Old, value for National Semiconductor CompactRISC.  Deprecated. ';
e_machine_strings[e_machine.XGATE] = 'Motorola XGATE embedded processor';
e_machine_strings[e_machine.C166] = 'Infineon C16x/XC16x processor';
e_machine_strings[e_machine.M16C] = 'Renesas M16C series microprocessors';
e_machine_strings[e_machine.DSPIC30F] = 'Microchip Technology dsPIC30F Digital Signal Controller';
e_machine_strings[e_machine.CE] = 'Freescale Communication Engine RISC core';
e_machine_strings[e_machine.M32C] = 'Renesas M32C series microprocessors';
e_machine_strings[e_machine.res121] = 'Reserved';
e_machine_strings[e_machine.res122] = 'Reserved';
e_machine_strings[e_machine.res123] = 'Reserved';
e_machine_strings[e_machine.res124] = 'Reserved';
e_machine_strings[e_machine.res125] = 'Reserved';
e_machine_strings[e_machine.res126] = 'Reserved';
e_machine_strings[e_machine.res127] = 'Reserved';
e_machine_strings[e_machine.res128] = 'Reserved';
e_machine_strings[e_machine.res129] = 'Reserved';
e_machine_strings[e_machine.res130] = 'Reserved';
e_machine_strings[e_machine.TSK3000] = 'Altium TSK3000 core';
e_machine_strings[e_machine.RS08] = 'Freescale RS08 embedded processor';
e_machine_strings[e_machine.res133] = 'Reserved';
e_machine_strings[e_machine.ECOG2] = 'Cyan Technology eCOG2 microprocessor';
e_machine_strings[e_machine.SCORE] = 'Sunplus Score';
e_machine_strings[e_machine.SCORE7] = 'Sunplus S+core7 RISC processor';
e_machine_strings[e_machine.DSP24] = 'New Japan Radio (NJR) 24-bit DSP Processor';
e_machine_strings[e_machine.VIDEOCORE3] = 'Broadcom VideoCore III processor';
e_machine_strings[e_machine.LATTICEMICO32] = 'RISC processor for Lattice FPGA architecture';
e_machine_strings[e_machine.SE_C17] = 'Seiko Epson C17 family';
e_machine_strings[e_machine.TI_C6000] = 'Texas Instruments TMS320C6000 DSP family';
e_machine_strings[e_machine.TI_C2000] = 'Texas Instruments TMS320C2000 DSP family';
e_machine_strings[e_machine.TI_C5500] = 'Texas Instruments TMS320C55x DSP family';
e_machine_strings[e_machine.res143] = 'Reserved';
e_machine_strings[e_machine.TI_PRU] = 'Texas Instruments Programmable Realtime Unit';
e_machine_strings[e_machine.res145] = 'Reserved';
e_machine_strings[e_machine.res146] = 'Reserved';
e_machine_strings[e_machine.res147] = 'Reserved';
e_machine_strings[e_machine.res148] = 'Reserved';
e_machine_strings[e_machine.res149] = 'Reserved';
e_machine_strings[e_machine.res150] = 'Reserved';
e_machine_strings[e_machine.res151] = 'Reserved';
e_machine_strings[e_machine.res152] = 'Reserved';
e_machine_strings[e_machine.res153] = 'Reserved';
e_machine_strings[e_machine.res154] = 'Reserved';
e_machine_strings[e_machine.res155] = 'Reserved';
e_machine_strings[e_machine.res156] = 'Reserved';
e_machine_strings[e_machine.res157] = 'Reserved';
e_machine_strings[e_machine.res158] = 'Reserved';
e_machine_strings[e_machine.res159] = 'Reserved';
e_machine_strings[e_machine.MMDSP_PLUS] = 'STMicroelectronics 64bit VLIW Data Signal Processor';
e_machine_strings[e_machine.CYPRESS_M8C] = 'Cypress M8C microprocessor';
e_machine_strings[e_machine.R32C] = 'Renesas R32C series microprocessors';
e_machine_strings[e_machine.TRIMEDIA] = 'NXP Semiconductors TriMedia architecture family';
e_machine_strings[e_machine.QDSP6] = 'QUALCOMM DSP6 Processor';
e_machine_strings[e_machine._8051] = 'Intel 8051 and variants';
e_machine_strings[e_machine.STXP7X] = 'STMicroelectronics STxP7x family';
e_machine_strings[e_machine.NDS32] = 'Andes Technology compact code size embedded RISC processor family';
e_machine_strings[e_machine.ECOG1] = 'Cyan Technology eCOG1X family';
e_machine_strings[e_machine.ECOG1X] = 'Cyan Technology eCOG1X family';
e_machine_strings[e_machine.MAXQ30] = 'Dallas Semiconductor MAXQ30 Core Micro-controllers';
e_machine_strings[e_machine.XIMO16] = 'New Japan Radio (NJR) 16-bit DSP Processor';
e_machine_strings[e_machine.MANIK] = 'M2000 Reconfigurable RISC Microprocessor';
e_machine_strings[e_machine.CRAYNV2] = 'Cray Inc. NV2 vector architecture';
e_machine_strings[e_machine.RX] = 'Renesas RX family';
e_machine_strings[e_machine.METAG] = 'Imagination Technologies Meta processor architecture';
e_machine_strings[e_machine.MCST_ELBRUS] = 'MCST Elbrus general purpose hardware architecture';
e_machine_strings[e_machine.ECOG16] = 'Cyan Technology eCOG16 family';
e_machine_strings[e_machine.CR16] = 'National Semiconductor CompactRISC 16-bit processor';
e_machine_strings[e_machine.ETPU] = 'Freescale Extended Time Processing Unit';
e_machine_strings[e_machine.SLE9X] = 'Infineon Technologies SLE9X core';
e_machine_strings[e_machine.L1OM] = 'Intel L1OM';
e_machine_strings[e_machine.K1OM] = 'Intel K1OM';
e_machine_strings[e_machine.INTEL182] = 'Reserved by Intel';
e_machine_strings[e_machine.AARCH64] = 'ARM 64-bit architecture';
e_machine_strings[e_machine.ARM184] = 'Reserved by ARM';
e_machine_strings[e_machine.AVR32] = 'Atmel Corporation 32-bit microprocessor family';
e_machine_strings[e_machine.STM8] = 'STMicroeletronics STM8 8-bit microcontroller';
e_machine_strings[e_machine.TILE64] = 'Tilera TILE64 multicore architecture family';
e_machine_strings[e_machine.TILEPRO] = 'Tilera TILEPro multicore architecture family';
e_machine_strings[e_machine.MICROBLAZE] = 'Xilinx MicroBlaze 32-bit RISC soft processor core';
e_machine_strings[e_machine.CUDA] = 'NVIDIA CUDA architecture';
e_machine_strings[e_machine.TILEGX] = 'Tilera TILE-Gx multicore architecture family';
e_machine_strings[e_machine.CLOUDSHIELD] = 'CloudShield architecture family';
e_machine_strings[e_machine.COREA_1ST] = 'KIPO-KAIST Core-A 1st generation processor family';
e_machine_strings[e_machine.COREA_2ND] = 'KIPO-KAIST Core-A 2nd generation processor family';
e_machine_strings[e_machine.ARC_COMPACT2] = 'Synopsys ARCompact V2';
e_machine_strings[e_machine.OPEN8] = 'Open8 8-bit RISC soft processor core';
e_machine_strings[e_machine.RL78] = 'Renesas RL78 family. ';
e_machine_strings[e_machine.VIDEOCORE5] = 'Broadcom VideoCore V processor';
e_machine_strings[e_machine._78K0R] = 'Renesas 78K0R. ';
e_machine_strings[e_machine._56800EX] = 'Freescale 56800EX Digital Signal Controller (DSC)';
e_machine_strings[e_machine.BA1] = 'Beyond BA1 CPU architecture';
e_machine_strings[e_machine.BA2] = 'Beyond BA2 CPU architecture';
e_machine_strings[e_machine.XCORE] = 'XMOS xCORE processor family';
e_machine_strings[e_machine.MCHP_PIC] = 'Microchip 8-bit PIC(r) family';
e_machine_strings[e_machine.INTELGT] = 'Intel Graphics Technology';
e_machine_strings[e_machine.INTEL206] = 'Reserved by Intel';
e_machine_strings[e_machine.INTEL207] = 'Reserved by Intel';
e_machine_strings[e_machine.INTEL208] = 'Reserved by Intel';
e_machine_strings[e_machine.INTEL209] = 'Reserved by Intel';
e_machine_strings[e_machine.KM32] = 'KM211 KM32 32-bit processor';
e_machine_strings[e_machine.KMX32] = 'KM211 KMX32 32-bit processor';
e_machine_strings[e_machine.KMX16] = 'KM211 KMX16 16-bit processor';
e_machine_strings[e_machine.KMX8] = 'KM211 KMX8 8-bit processor';
e_machine_strings[e_machine.KVARC] = 'KM211 KVARC processor';
e_machine_strings[e_machine.CDP] = 'Paneve CDP architecture family';
e_machine_strings[e_machine.COGE] = 'Cognitive Smart Memory Processor';
e_machine_strings[e_machine.COOL] = 'Bluechip Systems CoolEngine';
e_machine_strings[e_machine.NORC] = 'Nanoradio Optimized RISC';
e_machine_strings[e_machine.CSR_KALIMBA] = 'CSR Kalimba architecture family';
e_machine_strings[e_machine.Z80] = 'Zilog Z80';
e_machine_strings[e_machine.VISIUM] = 'Controls and Data Services VISIUMcore processor';
e_machine_strings[e_machine.FT32] = 'FTDI Chip FT32 high performance 32-bit RISC architecture';
e_machine_strings[e_machine.MOXIE] = 'Moxie processor family';
e_machine_strings[e_machine.AMDGPU] = 'AMD GPU architecture';
e_machine_strings[e_machine.RISCV] = 'RISC-V';
e_machine_strings[e_machine.LANAI] = 'Lanai 32-bit processor. ';
e_machine_strings[e_machine.CEVA] = 'CEVA Processor Architecture Family';
e_machine_strings[e_machine.CEVA_X2] = 'CEVA X2 Processor Family';
e_machine_strings[e_machine.BPF] = 'Linux BPF – in-kernel virtual machine. ';
e_machine_strings[e_machine.GRAPHCORE_IPU] = 'Graphcore Intelligent Processing Unit';
e_machine_strings[e_machine.IMG1] = 'Imagination Technologies';
e_machine_strings[e_machine.NFP] = 'Netronome Flow Processor. ';
e_machine_strings[e_machine.VE] = 'NEC Vector Engine';
e_machine_strings[e_machine.CSKY] = 'C-SKY processor family. ';
e_machine_strings[e_machine.ARC_COMPACT3_64] = 'Synopsys ARCv2.3 64-bit';
e_machine_strings[e_machine.MCS6502] = 'MOS Technology MCS 6502 processor';
e_machine_strings[e_machine.ARC_COMPACT3] = 'Synopsys ARCv2.3 32-bit';
e_machine_strings[e_machine.KVX] = 'Kalray VLIW core of the MPPA processor family';
e_machine_strings[e_machine._65816] = 'WDC 65816/65C816';
e_machine_strings[e_machine.LOONGARCH] = 'LoongArch';
e_machine_strings[e_machine.KF32] = 'ChipON KungFu32';
e_machine_strings[e_machine.U16_U8CORE] = 'LAPIS nX-U16/U8';
e_machine_strings[e_machine.TACHYUM] = 'Tachyum';
e_machine_strings[e_machine._56800EF] = 'NXP 56800EF Digital Signal Controller (DSC)';

//Note in C these are prefixed with PT_
export enum p_type {
	NULL = 0x00000000, //Program header table entry unused.
	LOAD = 0x00000001, //Loadable segment.
	DYNAMIC = 0x00000002, //Dynamic linking information.
	INTERP = 0x00000003, //Interpreter information.
	NOTE = 0x00000004, //Auxiliary information.
	SHLIB = 0x00000005, //Reserved.
	PHDR = 0x00000006, //Segment containing program header table itself.
	TLS = 0x00000007, //Thread-Local Storage template.
	//[LOOS - HIOS] Reserved inclusive range. Operating system specific.
	LOOS = 0x60000000,
	HIOS = 0x6fffffff,
	//[LOPROC - HIPROC] Reserved inclusive range. Processor specific.
	LOPROC = 0x70000000,
	HIPROC = 0x7fffffff,
}

export enum p_flags {
	READ = 4,
	WRITE = 2,
	EXECUTE = 1,
}

//Note in C these are prefixed with SHT_
export enum sh_type {
	NULL = 0x0, //Section header table entry unused
	PROGBITS = 0x1, //Program data
	SYMTAB = 0x2, //Symbol table
	STRTAB = 0x3, //String table
	RELA = 0x4, //Relocation entries with addends
	HASH = 0x5, //Symbol hash table
	DYNAMIC = 0x6, //Dynamic linking information
	NOTE = 0x7, //Notes
	NOBITS = 0x8, //Program space with no data (bss)
	REL = 0x9, //Relocation entries, no addends
	SHLIB = 0x0a, //Reserved
	DYNSYM = 0x0b, //Dynamic linker symbol table
	INIT_ARRAY = 0x0e, //Array of constructors
	FINI_ARRAY = 0x0f, //Array of destructors
	PREINIT_ARRAY = 0x10, //Array of pre-constructors
	GROUP = 0x11, //Section group
	SYMTAB_SHNDX = 0x12, //Extended section indices
	NUM = 0x13, //Number of defined types.
	LOOS = 0x60000000, //Start OS-specific.
}

//Note in C these are prefixed with SHF_
export enum sh_flags {
	WRITE = 0x1, //	Writable
	ALLOC = 0x2, //	Occupies memory during execution
	EXECINSTR = 0x4, //	Executable
	MERGE = 0x10, //	Might be merged
	STRINGS = 0x20, //	Contains null-terminated strings
	INFO_LINK = 0x40, //	'sh_info' contains SHT index
	LINK_ORDER = 0x80, //	Preserve order after combining
	OS_NONCONFORMING = 0x100, //	Non-standard OS specific handling required
	GROUP = 0x200, //	Section is member of a group
	TLS = 0x400, //	Section hold thread-local data
	MASKOS = 0x0ff00000, //	OS-specific
	MASKPROC = 0xf0000000, //	Processor-specific
	ORDERED = 0x4000000, //	Special ordering requirement (Solaris)
	EXCLUDE = 0x8000000, //	Section is excluded unless referenced or allocated (Solaris)
}

//Note in C these are prefixed with STT_
export enum st_type {
	NOTYPE = 0,
	OBJECT = 1,
	FUNC = 2,
	SECTION = 3,
	FILE = 4,
	COMMON = 5,
	TLS = 6,
}

//Note in C these are prefixed with STB_
export enum st_bindings {
	LOCAL = 0,
	GLOBAL = 1,
	WEAK = 2,
}

//Note in C these are prefixed with STV_
export enum st_visibility {
	DEFAULT = 0,
	INTERNAL = 1,
	HIDDEN = 2,
	PROTECTED = 3,
}

//Note in C these are prefixed with DT_
export enum d_tag {
	NULL = 0, // Marks end of dynamic section
	NEEDED = 1, // String table offset to name of a needed library
	PLTRELSZ = 2, // Size in bytes of PLT relocation entries
	PLTGOT = 3, // Address of PLT and/or GOT
	HASH = 4, // Address of symbol hash table
	STRTAB = 5, // Address of string table
	SYMTAB = 6, // Address of symbol table
	RELA = 7, // Address of Rela relocation table
	RELASZ = 8, // Size in bytes of the Rela relocation table
	RELAENT = 9, // Size in bytes of a Rela relocation table entry
	STRSZ = 10, // Size in bytes of string table
	SYMENT = 11, // Size in bytes of a symbol table entry
	INIT = 12, // Address of the initialization function
	FINI = 13, // Address of the termination function
	SONAME = 14, // String table offset to name of shared object
	RPATH = 15, // String table offset to library search path (deprecated)
	SYMBOLIC = 16, // Alert linker to search this shared object before the executable for symbols
	REL = 17, // Address of Rel relocation table
	RELSZ = 18, // Size in bytes of Rel relocation table
	RELENT = 19, // Size in bytes of a Rel table entry
	PLTREL = 20, // Type of relocation entry to which the PLT refers (Rela or Rel)
	DEBUG = 21, // Undefined use for debugging
	TEXTREL = 22, // Absence of this entry indicates that no relocation entries should apply to a nonwritable segment
	JMPREL = 23, // Address of relocation entries associated solely with the PLT
	BIND_NOW = 24, // Instruct dynamic linker to process all relocations before transferring control to the executable
	INIT_ARRAY = 25,
	FINI_ARRAY = 26,
	INIT_ARRAYSZ = 27,
	FINI_ARRAYSZ = 28,
	RUNPATH = 29, // String table offset to library search path
	FLAGS = 30,
	PREINIT_ARRAY = 32,
	PREINIT_ARRAYSZ = 33,
	SYMTAB_SHNDX = 34,
	RELRSZ = 35,
	RELR = 36,
	RELRENT = 37,
	ENCODING = 38,
	OLD_LOOS = 0x60000000,
	LOOS = 0x6000000d,
	HIOS = 0x6ffff000,
	VALRNGLO = 0x6ffffd00,
	GNU_FLAGS_1 = 0x6ffffdf4,
	GNU_PRELINKED = 0x6ffffdf5,
	GNU_CONFLICTSZ = 0x6ffffdf6,
	GNU_LIBLISTSZ = 0x6ffffdf7,
	CHECKSUM = 0x6ffffdf8,
	PLTPADSZ = 0x6ffffdf9,
	MOVEENT = 0x6ffffdfa,
	MOVESZ = 0x6ffffdfb,
	FEATURE = 0x6ffffdfc,
	POSFLAG_1 = 0x6ffffdfd,
	SYMINSZ = 0x6ffffdfe,
	VALRNGHI = 0x6ffffdff,
	SYMINENT = 0x6ffffdff,
	ADDRRNGLO = 0x6ffffe00,
	GNU_HASH = 0x6ffffef5,
	TLSDESC_PLT = 0x6ffffef6,
	TLSDESC_GOT = 0x6ffffef7,
	GNU_CONFLICT = 0x6ffffef8,
	GNU_LIBLIST = 0x6ffffef9,
	CONFIG = 0x6ffffefa,
	DEPAUDIT = 0x6ffffefb,
	AUDIT = 0x6ffffefc,
	PLTPAD = 0x6ffffefd,
	MOVETAB = 0x6ffffefe,
	ADDRRNGHI = 0x6ffffeff,
	SYMINFO = 0x6ffffeff,
	VERSYM = 0x6ffffff0,
	RELACOUNT = 0x6ffffff9,
	RELCOUNT = 0x6ffffffa,
	FLAGS_1 = 0x6ffffffb,
	VERDEF = 0x6ffffffc,
	VERDEFNUM = 0x6ffffffd,
	VERNEED = 0x6ffffffe,
	OLD_HIOS = 0x6fffffff,
	VERNEEDNUM = 0x6fffffff,
	LOPROC = 0x70000000,
	HIPROC = 0x7fffffff,
}
